export const MY_LEAVES_LIST = 'MY_LEAVES_LIST';
export const UPDATE_MY_LEAVES_LIST = 'UPDATE_MY_LEAVES_LIST';
export const APPLY_LEAVE = 'APPLY_LEAVE';
export const UPDATE_APPLY_LEAVE = 'UPDATE_APPLY_LEAVE';
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_GET_PROFILE = 'UPDATE_GET_PROFILE';

export const CHANGE_NAME = 'CHANGE_NAME';
export const UPDATE_CHANGE_NAME = 'UPDATE_CHANGE_NAME';

export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const UPDATE_CHANGE_EMAIL = 'UPDATE_CHANGE_EMAIL';

export const CHANGE_PHONE_NUM = 'CHANGE_PHONE_NUM';
export const UPDATE_CHANGE_PHONE_NUM = 'UPDATE_CHANGE_PHONE_NUM';

export const CHANGE_QUALIFICATION = 'CHANGE_QUALIFICATION';
export const UPDATE_CHANGE_QUALIFICATION = 'UPDATE_CHANGE_QUALIFICATION';

export const GET_MY_CLASSES = 'GET_MY_CLASSES';
export const UPDATE_GET_MY_CLASSES = 'UPDATE_GET_MY_CLASSES';

export const GET_CHAPTER_BY_SUBJECT = 'GET_CHAPTER_BY_SUBJECT,';
export const UPDATE_GET_CHAPTER_BY_SUBJECT = 'UPDATE_GET_CHAPTER_BY_SUBJECT';

export const GET_CONCEPT_BY_CHAPTER = 'GET_CONCEPT_BY_CHAPTER';
export const UPDATE_GET_CONCEPT_BY_CHAPTER = 'UPDATE_GET_CONCEPT_BY_CHAPTER';

export const GET_SUB_CONCEPT_BY_CONCEPT = 'GET_SUB_CONCEPT_BY_CONCEPT';
export const UPDATE_GET_SUB_CONCEPT_BY_CONCEPT = 'GET_SUB_CONCEPT_BY_CONCEPT';

export const CHANGE_UNVIERSITY = 'CHANGE_UNVIERSITY';
export const UPDATE_CHANGE_UNVIERSITY = 'UPDATE_CHANGE_UNVIERSITY';
