export const MY_LEAVES_LIST = 'MY_LEAVES_LIST';
export const UPDATE_MY_LEAVES_LIST = 'UPDATE_MY_LEAVES_LIST';
export const APPLY_LEAVE = 'APPLY_LEAVE';
export const UPDATE_APPLY_LEAVE = 'UPDATE_APPLY_LEAVE';
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_GET_PROFILE = 'UPDATE_GET_PROFILE';
