export const LOGIN = 'LOGIN';
export const UPDATE_LOGIN = 'UPDATE_LOGIN';

export const REGISTER = 'REGISTER';
export const UPDATE_REGISTER = 'UPDATE_REGISTER';

export const CO_CURRICULAR_ACTIVITIES = 'CO_CURRICULAR_ACTIVITIES';
export const UPDATE_CO_CURRICULAR_ACTIVITIES = 'UPDATE_CO_CURRICULAR_ACTIVITIES';

export const SEND_OTP = 'SEND_OTP';
export const UPDATE_SEND_OTP = 'UPDATE_SEND_OTPs';

export const GET_ALL_GRADES = 'GET_ALL_GRADES';
export const UPDATE_GET_ALL_GRADES = 'UPDATE_GET_ALL_GRADES';

export const GET_UNIQUE_SUBJECTS = 'GET_UNIQUE_SUBJECTS';
export const UPDATE_GET_UNIQUE_SUBJECTS = 'UPDATE_GET_UNIQUE_SUBJECTS';
