export const LOGIN = 'LOGIN';
export const UPDATE_LOGIN = 'UPDATE_LOGIN';
export const CLEAR_LOGIN = 'CLEAR_LOGIN';
export const SET_LOGIN_LOADING = 'SET_LOGIN_LOADING';

export const REGISTER = 'REGISTER';
export const UPDATE_REGISTER = 'UPDATE_REGISTER';

export const CO_CURRICULAR_ACTIVITIES = 'CO_CURRICULAR_ACTIVITIES';
export const UPDATE_CO_CURRICULAR_ACTIVITIES = 'UPDATE_CO_CURRICULAR_ACTIVITIES';

export const SEND_OTP = 'SEND_OTP';
export const UPDATE_SEND_OTP = 'UPDATE_SEND_OTPs';

export const IS_SENDING_OTP = 'IS_SENDING_OTP';

export const VERIFY_OTP = 'VERIFY_OTP';
export const UPDATE_VERIFY_OTP = 'UPDATE_VERIFY_OTP';

export const GET_ALL_GRADES = 'GET_ALL_GRADES';
export const UPDATE_GET_ALL_GRADES = 'UPDATE_GET_ALL_GRADES';

export const GET_UNIQUE_SUBJECTS = 'GET_UNIQUE_SUBJECTS';
export const UPDATE_GET_UNIQUE_SUBJECTS = 'UPDATE_GET_UNIQUE_SUBJECTS';

export const GET_SUBJECTS_BY_CLASS = 'GET_SUBJECTS_BY_CLASS';
export const UPDATE_GET_SUBJECTS_BY_CLASS = 'UPDATE_GET_SUBJECTS_BY_CLASS';
export const  REGISTER_TEACHER = 'REGISTER_TEACHER';
export const  UPDATE_REGISTER_TEACHER = 'UPDATE_REGISTER_TEACHER';

export const GET_TIMESLOTS = 'GET_TIMESLOTS';
export const UPDATE_GET_TIMESLOTS = 'UPDATE_GET_TIMESLOTS';

export const GET_UNIVERSITIES = 'GET_UNIVERSITIES';
export const UPDATE_GET_UIVERSITIES = 'UPDATE_GET_UIVERSITIES';

export const GET_SUBJECTS = 'GET_SUBJECTS';
export const UPDATE_GET_SUBJECTS = 'UPDATE_GET_SUBJECTS';

export const GET_QUALIFICATIONS = 'GET_QUALIFICATIONS';
export const UPDATE_GET_QUALIFICATIONS = 'UPDATE_GET_QUALIFICATIONS';

export const GET_COUNTRY_LIST = 'GET_COUNTRY_LIST';
export const UPDATE_GET_COUNTRY_LIST = 'UPDATE_GET_COUNTRY_LIST';

export const GET_STATE_LIST = 'GET_STATE_LIST';
export const UPDATE_GET_STATE_LIST = 'UPDATE_GET_STATE_LIST';
