const sidebar = [
    'Questions 1',
    'Questions 2',
    'Questions 3',
    'Questions 4',
    'Questions 5',
    'Questions 6',
    'Questions 7',
    'Questions 8',
    'Questions 9',
    'Questions 10',
    'Questions 11',
    'Questions 12',
    'Questions 13',
    'Questions 14',
    'Questions 15',
    'Questions 16',
    'Questions 17',
    'Questions 18',
    'Questions 19',
    'Questions 20',
    'Questions 21',
    'Questions 22',
    'Questions 23',
    'Questions 24',
    'Questions 25',
    'Questions 26',
    'Questions 27',
    'Questions 28',
    'Questions 29',
    'Questions 30',
];

export default sidebar;
