export const GET_ALL_BRAIN_GYM = 'GET_ALL_BRAIN_GYM';
export const BRAIN_GYM_ALLGYM = 'GET_ALL_BRAIN_GYM';
export const BRAIN_GYM_ALLGYM_UPDATED = 'BRAIN_GYM_ALLGYM_UPDATED';

export const GET_MASTER_BRAIN_GYM_BY_ID = 'GET_MASTER_BRAIN_GYM_BY_ID';
export const UPDATE_MASTER_BRAIN_GYM_BY_ID = 'UPDATE_MASTER_BRAIN_GYM_BY_ID';

export const GET_QUESTIONS_BY_TAG = 'GET_QUESTIONS_BY_TAG';
export const UPDATE_QUESTION_BY_TAG = 'UPDATE_QUESTION_BY_TAG';

export const ATTEMPT_QUESTION = 'ATTEMPT_QUESTION';
export const UPDATE_ATTEMPT_QUESTION = 'UPDATE_ATTEMPT_QUESTION';

export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const SET_LOADING = 'SET_LOADING';

export const SET_CHEST_DATA = 'SET_CHEST_DATA';

export const SET_QUESTION_COUNTER = 'SET_QUESTION_COUNTER';

export const COMPLETE_CHEST = 'COMPLETE_CHEST';

export const SET_UNLOCK_CHEST = 'SET_UNLOCK_CHEST';
export const UPDATE_UNLOCK_CHEST = 'UPDATE_UNLOCK_CHEST';
