export const BRAIN_GYM_ALLGYM = 'BRAIN_GYM_ALLGYM';
export const BRAIN_GYM_ALLGYM_UPDATED = 'BRAIN_GYM_ALLGYM_UPDATED';

export const BRAIN_GYM_GETMASTERID = 'BRAIN_GYM_GETMASTERID';
export const BRAIN_GYM_GETMASTERID_UPDATED= 'BRAIN_GYM_GETMASTERID_UPDATED';

export const QUESTIONS_GET_QUESTION_BY_TAG = 'QUESTIONS_GET_QUESTION_BY_TAG';
export const QUESTIONS_GET_QUESTION_BY_TAG_UPDATED = 'QUESTIONS_GET_QUESTION_BY_TAG_UPDATED';

export const QUESTIONS_ATTEMPT_QUESTION = 'QUESTIONS_ATTEMPT_QUESTION';
export const QUESTIONS_ATTEMPT_QUESTION_UPDATED = 'QUESTIONS_ATTEMPT_QUESTION_UPDATED';

export const GET_USERS_FAILED = 'GET_USERS_FAILED';

