export const START_CHEST = 'START_CHEST';
export const UPDATE_START_CHEST = 'UPDATE_START_CHEST';
export const GET_QUESTION_IN_CHEST = 'GET_QUESTION_IN_CHEST';
export const UPDATE_GET_QUESTION_IN_CHEST = 'UPDATE_GET_QUESTION_IN_CHEST';
export const ATTEMPT_QUESTION = 'ATTEMPT_QUESTION';
export const UPDATE_ATTEMPT_QUESTION = 'UPDATE_ATTEMPT_QUESTION';
export const COMPLETE_CHEST = 'COMPLETE_CHEST';
export const UPDATE_COMPLETE_CHEST = 'UPDATE_COMPLETE_CHEST';
